### ISSUE TITLE
CompleteMultipartUpload  parts.last raises exception

### ISSUE THREAD

**Issue by akiradeveloper** [akiradeveloper/akashic-storage#14]
almost no clue to solve this problem.

Seq#last:
Exceptions thrown
NoSuchElementException If the traversable collection is empty.

``` scala
      val lastPartNumber = parts.last.partNumber
```

Request("POST /hoge-36kp5mui93t3h41zet8saher-265/mymultipart?uploadId=1-DvgLkN1jfFDTCT", from /127.0.0.1:57629)
-> Complete Multipart Upload
java.util.NoSuchElementException
Jan 23, 2016 6:09:29 AM com.twitter.util.RootMonitor$ handle
SEVERE: Exception propagated to the root monitor!
java.util.NoSuchElementException
    at scala.collection.LinearSeqOptimized$class.last(LinearSeqOptimized.scala:148)
    at scala.collection.immutable.List.last(List.scala:84)
    at akashic.storage.service.CompleteMultipartUpload$t.runOnce(CompleteMultipartUpload.scala:60)
    at akashic.storage.service.CompleteMultipartUpload$t.runOnce(CompleteMultipartUpload.scala:27)
    at akashic.storage.service.Task$class.run(Task.scala:18)
    at akashic.storage.service.CompleteMultipartUpload$t.run(CompleteMultipartUpload.scala:27)
    at akashic.storage.service.CompleteMultipartUpload$$anonfun$2.apply(CompleteMultipartUpload.scala:26)
    at akashic.storage.service.CompleteMultipartUpload$$anonfun$2.apply(CompleteMultipartUpload.scala:26)
    at scala.Function1$$anonfun$andThen$1.apply(Function1.scala:55)
    at io.finch.Output$class.traverse(Output.scala:73)
    at io.finch.Output$Payload.traverse(Output.scala:172)

**Comment by akiradeveloper** [comment]
I will clean up issues tagged with s3-tests for now
