### ISSUE TITLE
s3test doesn't run

### ISSUE THREAD

**Issue by akiradeveloper** [akiradeveloper/akashic-storage#29]
I know this degradation happened at this commit https://github.com/akiradeveloper/akashic-storage/commit/665bfae76585b968cd5968167df5082f4963e551

I should fix this immediately
## ERROR: test suite for <module 's3tests.functional' from '/home/travis/build/akiradeveloper/akashic-storage/s3-tests/s3-tests-clone/s3tests/functional/__init__.py'>

Traceback (most recent call last):
  File "/home/travis/build/akiradeveloper/akashic-storage/s3-tests/s3-tests-clone/virtualenv/local/lib/python2.7/site-packages/nose/suite.py", line 209, in run
    self.setUp()
  File "/home/travis/build/akiradeveloper/akashic-storage/s3-tests/s3-tests-clone/virtualenv/local/lib/python2.7/site-packages/nose/suite.py", line 292, in setUp
    self.setupContext(ancestor)
  File "/home/travis/build/akiradeveloper/akashic-storage/s3-tests/s3-tests-clone/virtualenv/local/lib/python2.7/site-packages/nose/suite.py", line 315, in setupContext
    try_run(context, names)
  File "/home/travis/build/akiradeveloper/akashic-storage/s3-tests/s3-tests-clone/virtualenv/local/lib/python2.7/site-packages/nose/util.py", line 471, in try_run
    return func()
  File "/home/travis/build/akiradeveloper/akashic-storage/s3-tests/s3-tests-clone/s3tests/functional/**init**.py", line 352, in setup
    nuke_prefixed_buckets(prefix=prefix)
  File "/home/travis/build/akiradeveloper/akashic-storage/s3-tests/s3-tests-clone/s3tests/functional/**init**.py", line 111, in nuke_prefixed_buckets
    nuke_prefixed_buckets_on_conn(prefix, name, conn)
  File "/home/travis/build/akiradeveloper/akashic-storage/s3-tests/s3-tests-clone/s3tests/functional/**init**.py", line 63, in nuke_prefixed_buckets_on_conn
    for bucket in conn.get_all_buckets():
  File "/home/travis/build/akiradeveloper/akashic-storage/s3-tests/s3-tests-clone/virtualenv/local/lib/python2.7/site-packages/boto/s3/connection.py", line 437, in get_all_buckets
    response = self.make_request('GET', headers=headers)
  File "/home/travis/build/akiradeveloper/akashic-storage/s3-tests/s3-tests-clone/virtualenv/local/lib/python2.7/site-packages/boto/s3/connection.py", line 665, in make_request
    retry_handler=retry_handler
  File "/home/travis/build/akiradeveloper/akashic-storage/s3-tests/s3-tests-clone/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 1071, in make_request
    retry_handler=retry_handler)
  File "/home/travis/build/akiradeveloper/akashic-storage/s3-tests/s3-tests-clone/virtualenv/local/lib/python2.7/site-packages/boto/connection.py", line 1030, in _mexe
    raise ex
error: [Errno 111] Connection refused

**Comment by akiradeveloper** [comment]
The thing is the server isn't listening on the port! Wow and Why!

```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:3306            0.0.0.0:*               LISTEN      988/mysqld      
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1031/sshd       
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      1228/postgres   
tcp        0      0 10.240.0.167:48880      169.254.169.254:80      ESTABLISHED 3986/python     
tcp        0      0 10.240.0.167:48885      169.254.169.254:80      ESTABLISHED 1374/python     
tcp        0    208 10.240.0.167:22         104.197.186.159:56639   ESTABLISHED 1612/sshd: travis [
tcp        0      0 10.240.0.167:48188      169.254.169.254:80      ESTABLISHED 1373/python     
tcp        0      0 10.240.0.167:48879      169.254.169.254:80      TIME_WAIT   -               
tcp        0      0 10.240.0.167:58108      173.255.118.228:80      TIME_WAIT   -               
tcp6       0      0 :::22                   :::*                    LISTEN      1031/sshd   
```

**Comment by akiradeveloper** [comment]
I support it is server is immediately closed when  the program quits from App. So we need Await.ready there

Not sure why it was the commit turned into failure but the compactor thread running keeps the process from being killed? The commit purged compactor and there was a threadpool.
